name: Run Python Script

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.3  # Specify the Python version you want to use

    - name: Install dependencies (if needed)
      run: | 
        pip install  forex-python
        pip install requests
        

    - name: Run Python script
      run: python python-currency-converter/
      working-directory: python-currency-converter 
      
