name: Run Python Script

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.x  # Specify the Python version you want to use

    - name: Install dependencies (if needed)
      run: | 
        pip install forex-python
        pip install requests

    - name: find the python script 
      run: |
        for folder in */; do
          if [ -f "$Currency_Converter/currency_converter.py" ]; then
            echo "Running script in folder: $Currency_Converter"
            python "$Currency_Converter/currency_converter.py" 1.5 USD to GBP
            break  # Exit the loop once the script is found and executed
          fi
        done
      working-directory: ${{ github.workspace }}
     
      

      
